// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Profile struct {
	ProfileID int32       `json:"profile_id"`
	UserID    uuid.UUID   `json:"user_id"`
	Phone     pgtype.Text `json:"phone"`
	Address   pgtype.Text `json:"address"`
}

type User struct {
	UserID    uuid.UUID   `json:"user_id"`
	Username  string      `json:"username"`
	Email     string      `json:"email"`
	CreatedAt time.Time   `json:"created_at"`
	Phone     pgtype.Text `json:"phone"`
	Age       pgtype.Int4 `json:"age"`
	Password  pgtype.Text `json:"password"`
	Status    pgtype.Int4 `json:"status"`
	Level     pgtype.Int4 `json:"level"`
}
