// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	UserID       int32     `json:"user_id"`
	ID           uuid.UUID `json:"id"`
	UserEmail    string    `json:"user_email"`
	UserPassword string    `json:"user_password"`
	UserFullName string    `json:"user_full_name"`
	// user age must be between 1 and 100
	UserAge *int32 `json:"user_age"`
	// 1: active, 2: inactive, 3: deleted
	UserStatus int32     `json:"user_status"`
	UserLevel  int32     `json:"user_level"`
	CreatedAt  time.Time `json:"created_at"`
	UpdateAt   time.Time `json:"update_at"`
	DeleteAt   time.Time `json:"delete_at"`
}
