// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, email, age, password, status, level)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING user_id, username, email, created_at, phone, age, password, status, level
`

type CreateUserParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Age      pgtype.Int4 `json:"age"`
	Password pgtype.Text `json:"password"`
	Status   pgtype.Int4 `json:"status"`
	Level    pgtype.Int4 `json:"level"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.Age,
		arg.Password,
		arg.Status,
		arg.Level,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
		&i.Age,
		&i.Password,
		&i.Status,
		&i.Level,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, created_at, phone, age, password, status, level FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
		&i.Age,
		&i.Password,
		&i.Status,
		&i.Level,
	)
	return i, err
}
