CREATE EXTENSION IF NOT EXISTS "pgcrypto";

--- Create table
CREATE TABLE IF NOT EXISTS users (
	user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id  UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
	user_email VARCHAR(100) NOT NULL UNIQUE ,
	user_password VARCHAR(100) NOT NULL,
	user_full_name VARCHAR(100) NOT NULL,
	user_age INT CHECK (user_age >= 1 AND user_age <= 100),
	user_status INT NOT NULL DEFAULT 1 CHECK (user_status IN (1, 2, 3)),
	user_level INT NOT NULL DEFAULT 1 CHECK (user_level IN (1, 2, 3)),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	update_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	delete_at TIMESTAMPTZ DEFAULT NULL
);

-- Create comment
COMMENT ON COLUMN users.user_age IS 'user age must be between 1 and 100';
COMMENT ON COLUMN users.user_status IS '1: active, 2: inactive, 3: deleted';

--- Create index
CREATE INDEX IF NOT EXISTS idx_users_level ON users (user_level);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (user_status);

--- Create trigger 
CREATE OR REPLACE FUNCTION update_users_update_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.update_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER set_created_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_users_update_at();
